[cloud1]
i-03564c799e246b853 ansible_connection=aws_ssm ansible_aws_ssm_region=ap-northeast-1 ansible_aws_ssm_bucket_name=cloud1-ssm-ansible-20260401050212281000000001 ec2_public_ip=3.112.39.159

[cloud1:vars]
ansible_python_interpreter=/usr/bin/python3
